name: Run vip Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/30 * * * *'

jobs:
  run_vip_workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: binary by @VIP
        run: chmod +x VIP
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install required packages
        run: |
          pip install telebot flask aiogram pyTelegramBotAPI python-telegram-bot

      - name: Run VIP.py
        run: python3 VIP.py
